# Generated by Django 3.0.5 on 2020-05-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('givenname', models.CharField(max_length=100)),
                ('familyname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100)),
                ('imageurl', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('end_date', models.DateField()),
                ('topic', models.TextField()),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField()),
                ('public', models.BooleanField()),
                ('flag', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.Categories')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.Users')),
            ],
            options={
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('optiontext', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.Polls')),
            ],
            options={
                'db_table': 'poll_options',
            },
        ),
        migrations.CreateModel(
            name='PollResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.PollOptions')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.Polls')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingplace.Users')),
            ],
            options={
                'db_table': 'poll_responses',
                'unique_together': {('uid', 'pid')},
            },
        ),
    ]
